import '@/global.css'
import type { Metadata } from 'next'
import ProviderClient from './ProviderClient'
import { ReactNode } from 'react'
import Wrapper from '@/modules/shared/components/Wrapper'
import '../modules/shared/stylesheet/shared.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className="t">
        <ProviderClient>
          {/* <Header /> */}
          <Wrapper>{children}</Wrapper>
          {/* <Footer /> */}
        </ProviderClient>
      </body>
    </html>
  )
}
